nicknames = {
    "orin" : "Rin Kaenbyou",
    "okuu" : "Utsuho Reiuji",
    "merry" : "Maribel Hearn",
    "banki-chan" : "Sekibanki",
    "patchy" : "Patchouli Knowledge",
    "wakasagi" : "Wakasagihime",
    "bucket" : "Kisume",
    "flan" : "Flandre",
    "baka" : "Cirno",
    "9" : "Cirno",
    "mom" : "Junko",
    "clown" : "Clownpiece",
    "heca" : "Hecatia",
    "cumlord" : "Genji",


    # Eiki Shiki
    "eiki shiki, yamaxanadu" : "Eiki Shiki",
    "eiki shiki yamaxanadu" : "Eiki Shiki",
    "shiki eiki, yamaxanadu" : "Eiki Shiki",
    "shiki eiki yamaxanadu" : "Eiki Shiki",
    "yamaxanadu" : "Eiki Shiki",

    # JP Name Order
    "sakata nemuno" : "Nemuno Sakata",
    "teireida mai" : "Mai Teireida",
    "tsukumo yatsuhashi" : "Yatsuhashi Tsukumo",
    "meiling hong" : "Hong Meiling",
    "haniyasushin keiki" : "Keiki Haniyasushin",
    "scarlet flandre" : "Flandre Scarlet",
    "yorigami shion" : "Shion Yorigami",
    "joutouguu mayumi" : "Mayumi Joutouguu",
    "kagiyama hina" : "Hina Kagiyama",
    "kijin seija" : "Seija Kijin",
    "kochiya sanae" : "Sanae Kochiya",
    "houjuu nue" : "Nue Houjuu",
    "iizunamaru megumu" : "Megumu Iizunamaru",
    "morichika rinnosuke" : "Rinnosuke Morichika",
    "hoshiguma yuugi" : "Yuugi Hoshiguma",
    "margatroid alice" : "Alice Margatroid",
    "knowledge patchouli" : "Patchouli Knowledge",
    "futatsuiwa mamizou" : "Mamizou Futatsuiwa",
    "motoori kosuzu" : "Kosuzu Motoori",
    "inubashiri momiji" : "Momiji Inubashiri",
    "yatadera narumi" : "Narumi Yatadera",
    "hakurei reimu" : "Reimu Hakurei",
    "kazami yuuka" : "Yuuka Kazami",
    "komeiji satori" : "Satori Komeiji",
    "yorigami joon" : "Joon Yorigami",
    "kishin sagume" : "Sagume Kishin",
    "kumoi ichirin" : "Ichirin Kumoi",
    "hearn maribel" : "Maribel Hearn",
    "aki shizuha" : "Shizuha Aki",
    "moriya suwako" : "Suwako Moriya",
    "yakumo ran" : "Ran Yakumo",
    "izayoi sakuya" : "Sakuya Izayoi",
    "miyako yoshika" : "Yoshika Miyako",
    "komano aunn" : "Aunn Komano",
    "prismriver lyrica" : "Lyrica Prismriver",
    "horikawa raiko" : "Raiko Horikawa",
    "kaku seiga" : "Seiga Kaku",
    "toramaru shou" : "Shou Toramaru",
    "komeiji koishi" : "Koishi Komeiji",
    "kawashiro nitori" : "Nitori Kawashiro",
    "anaberal kana" : "Kana Anaberal",
    "seija kijin" : "Kijin Seija",
    "goutokuji mike" : "Mike Goutokuji",
    "imaizumi kagerou" : "Kagerou Imaizumi",
    "komakusa sannyo" : "Sannyo Komakusa",
    "tamatsukuri misumaru" : "Misumaru Tamatsukuri",
    "shiki eiki" : "Eiki Shiki",
    "niwatari kutaka" : "Kutaka Niwatari",
    "yamashiro takane" : "Takane Yamashiro",
    "kurodani yamame" : "Yamame Kurodani",
    "kitashirakawa chiyuri" : "Chiyuri Kitashirakawa",
    "okazaki yumemi" : "Yumemi Okazaki",
    "satsuki rin" : "Rin Satsuki",
    "nightbug wriggle" : "Wriggle Nightbug",
    "milk sunny" : "Sunny Milk",
    "ushizaki urumi" : "Urumi Ushizaki",
    "mizuhashi parsee" : "Parsee Mizuhashi",
    "prismriver merlin" : "Merlin Prismriver",
    "hijiri byakuren" : "Byakuren Hijiri",
    "kicchou yachie" : "Yachie Kicchou",
    "reiuji utsuho" : "Utsuho Reiuji",
    "matara okina" : "Okina Matara",
    "sukuna shinmyoumaru" : "Shinmyoumaru Sukuna",
    "shameimaru aya" : "Aya Shameimaru",
    "tsukumo benben" : "Benben Tsukumo",
    "tenkyuu chimata" : "Chimata Tenkyuu",
    "kaenbyou rin" : "Rin Kaenbyou",
    "asakura rikako" : "Rikako Asakura",
    "houraisan kaguya" : "Kaguya Houraisan",
    "kurokoma saki" : "Saki Kurokoma",
    "tatara kogasa" : "Kogasa Tatara",
    "lapislazuli hecatia" : "Hecatia Lapislazuli",
    "saigyouji yuyuko" : "Yuyuko Saigyouji",
    "scarlet remilia" : "Remilia Scarlet",
    "aki minoriko" : "Minoriko Aki",
    "kasodani kyouko" : "Kyouko Kasodani",
    "himemushi momoyo" : "Momoyo Himemushi",
    "ibaraki kasen" : "Kasen Ibaraki",
    "hinanawi tenshi" : "Tenshi Hinanawi",
    "inaba tewi" : "Tewi Inaba",
    "usami sumireko" : "Sumireko Usami",
    "yakumo yukari" : "Yukari Yakumo",
    "konpaku youmu" : "Youmu Konpaku",
    "murasa minamitsu" : "Minamitsu Murasa",
    "yasaka kanako" : "Kanako Yasaka",
    "okunoda miyoi" : "Miyoi Okunoda",
    "yagokoro eirin" : "Eirin Yagokoro",
    "onozuka komachi" : "Komachi Onozuka",
    "kudamaki tsukasa" : "Tsukasa Kudamaki",
    "prismriver lunasa" : "Lunasa Prismriver",
    "nishida satono" : "Satono Nishida",
    "usami renko" : "Renko Usami",
    "himekaidou hatate" : "Hatate Himekaidou",
    "ibuki suika" : "Suika Ibuki",
    "kamishirasawa keine" : "Keine Kamishirasawa",
    "ebisu eika" : "Eika Ebisu",
    "nagae iku" : "Iku Nagae",
    "kirisame marisa" : "Marisa Kirisame"

}